const types = {
  FILL_CHARACTERS: "FILL_CHARACTERS",
  CLEAR_CHARACTERS: "CLEAR_CHARACTERS",
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",

  SET_PAGE: "SET_PAGE",
};

export default types;
